extends SceneTree
## 独立存档验证正式通关解锁，不触碰玩家存档。
func _initialize() -> void:run.call_deferred()
func run() -> void:
	var save=load("res://src/services/save/save_service.gd").new()
	var folder:=ProjectSettings.globalize_path("res://../Levels/output")
	save.configure_storage_paths(folder+"/unlock-check.json",folder+"/unlock-check.tmp",folder+"/unlock-check.bak")
	save.data=save.default_data()
	var catalog=load("res://content/catalogs/mvp_catalog.tres")
	var planning:=PlanningParameters.read()
	assert(planning.errors.is_empty())
	var stages=catalog.stages
	for stage in stages:
		stage.resolve_dependencies_sync()
		PlanningParameters.apply_values(stage.reward,"reward:"+stage.stage_id,planning)
		assert(stage.song.audio_stream!=null)
	assert(save.is_stage_unlocked(stages[0]))
	assert(not save.is_stage_unlocked(stages[1]))
	assert(not save.is_stage_unlocked(stages[2]))
	save.record_stage_result(stages[0],{"cleared":false})
	assert(not save.is_stage_unlocked(stages[1]))
	save.record_stage_result(stages[0],{"cleared":true})
	assert(save.is_stage_unlocked(stages[1]))
	assert(not save.is_stage_unlocked(stages[2]))
	save.record_stage_result(stages[1],{"cleared":true})
	assert(save.is_stage_unlocked(stages[2]))
	save.load_or_create()
	assert(save.is_stage_unlocked(stages[2]))
	assert(not save.debug_grant_pet("pet_gui_jin_yang",true))
	assert(is_equal_approx(float(stages[2].stage_show.level_data.objects[0].fields.scale[0]),1.2))
	var cards=load("res://content/level_cards/default_level_card_catalog.tres")
	for i in 3:assert(cards.cards[i].stage_id==stages[i].stage_id)
	save.free()
	print("PASS 新存档只开钟；失败不解锁；钟→火→牲逐关通关解锁且重载保持；宠物开发授予关闭；音频与卡片入口完整")
	quit()
